// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"false","Made with MV Image":"SMM","Show Custom Splash":"true","Custom Image":"SMM","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}}
];
