// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"SAN_ShaderFilter","status":true,"description":"シェーダーフィルター 1.0.0\r\nシェーダーフィルターによる視覚エフェクト","parameters":{}},
{"name":"SAN_ShaderFilterCharaRipple","status":true,"description":"キャラクター波紋エフェクトフィルター 1.0.0\r\nキャラクターの周囲に波紋のエフェクトを表示するフィルターです。","parameters":{}},
{"name":"SAN_ShaderFilterCharaHeatHaze","status":true,"description":"キャラクター陽炎エフェクトフィルター 1.0.0\r\nキャラクターの周囲に陽炎のエフェクトを表示するフィルターです。","parameters":{}},
{"name":"SAN_ShaderFilterScanLine","status":true,"description":"走査線エフェクトフィルター 1.0.0\r\nスプライトに走査線のエフェクトを表示するフィルターです。","parameters":{}}
];
