// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Gacha","status":true,"description":"ランダムにアイテムを取得します。","parameters":{"Help Message Text":"1回Required Amount\\Gでガチャを引きます","Button Text":"ガチャを引く","Get Message Text":"GET Item Name","Show Item Description":"0","Effect":"121","Rank1 Effect":"122","Rank2 Effect":"123","Rank3 Effect":"124","Rank4 Effect":"125","Rank5 Effect":"126","ME":"Victory1","Required Amount":"100"}},
{"name":"GachaBook","status":true,"description":"ガチャアイテム一覧を表示します。","parameters":{"Unknown Data":"??????","Price Text":"Price","Equip Text":"Equip","Type Text":"Type","Rank Text":"Rank","Simple Display":"1"}}
];
